//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAPIApplication.Models.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int id { get; set; }
        public int id_unit { get; set; }
        public int id_country_code { get; set; }
        public string name_city { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
    
        public virtual Lookup Lookup { get; set; }
        public virtual Lookup Lookup1 { get; set; }
    }
}
